spring:
  application:
    name: backend
  jackson:
    serialization:
      indent_output: true
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:mysql://localhost:3307/hishatakaran
    username: hishatakaranlogin
    password: hishatakaranpassword
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  sql:
    init:
      mode: ALWAYS
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      enabled: true
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  servlet:
    session:
      cookie:
        http-only: true
        secure: false
      store-type: jdbc
      timeout: 8h
  port: 8888

app:
  api:
    swagger:
      enable: true

gemini:
  api:
    key: ${GEMINI_API_KEY}