spring:
  application:
    name: backend
  jackson:
    serialization:
      indent_output: true
  datasource:
    url: jdbc:mysql://localhost:3307/hishatakaran
    username: hishatakaranlogin
    password: hishatakaranpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: NEVER
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8888

app:
  api:
    swagger:
      enable: true