insert into regions(id, name_hy, name_en, name_fr)
values
    (1, 'Ասկերանի շրջան', 'Askerani District', 'district d''Askerani'),
    (2, 'Հադրութի շրջան', 'Hadruti District', 'district de Hadruti'),
    (3, 'Մարտակերտի շրջան', 'Martakerti District', 'district de Martakerti'),
    (4, 'Մարտունու շրջան', 'Martunu District', 'district de Martunu'),
    (5, 'Նոր Շահումյանի (Քարվաճառ) շրջան', 'New Shahumyani (Kʻarvachar) District', 'district de Nouveau Shahumyani (Kʻarvachar)'),
    (6, 'Շահումյանի շրջան', 'Shahumyani District', 'district de Shahumyani'),
    (7, 'Շուշիի շրջան', 'Shushii District', 'district de Shushii'),
    (8, 'Ստեփանակերտ', 'Stepʻanakert', 'Stepʻanakert'),
    (9, 'Քաշաթաղի շրջան', 'Kʻashatʻaghi District', 'district de Kʻashatʻaghi');

insert into settlements(id, name_en, name_fr, name_hy, region)
values
    (1,  'Akna', 'Akna', 'Ակնա', 1),
    (2,  'Aknaghbyur', 'Aknaghbyur', 'Ակնաղբյուր', 1),
    (3,  'Aygestan', 'Aygestan', 'Այգեստան', 1),
    (4,  'Askeran', 'Askeran', 'Ասկերան', 1),
    (5,  'Astghashen', 'Astghashen', 'Աստղաշեն', 1),
    (6,  'Avetaranotsʻ', 'Avetaranotsʻ', 'Ավետարանոց', 1),
    (7,  'Armenakavan', 'Armenakavan', 'Արմենակավան', 1),
    (8,  'Berkʻadzor', 'Berkʻadzor', 'Բերքաձոր', 1),
    (9,  'Dahraz', 'Dahraz', 'Դահրազ', 1),
    (10, 'Dahrav', 'Dahrav', 'Դահրավ', 1),
    (11, 'Dashushen', 'Dashushen', 'Դաշուշեն', 1),
    (12, 'Ivanyan', 'Ivanyan', 'Իվանյան', 1),
    (13, 'Lusadzor', 'Lusadzor', 'Լուսաձոր', 1),
    (14, 'Khantsʻkʻ', 'Khantsʻkʻ', 'Խանցք', 1),
    (15, 'Khachen', 'Khachen', 'Խաչեն', 1),
    (16, 'Khachmach', 'Khachmach', 'Խաչմաչ', 1),
    (17, 'Khnatsʻakh', 'Khnatsʻakh', 'Խնածախ', 1),
    (18, 'Khnapat', 'Khnapat', 'Խնապատ', 1),
    (19, 'Khndzristan', 'Khndzristan', 'Խնձրիստան', 1),
    (20, 'Khramort', 'Khramort', 'Խրամորթ', 1),
    (21, 'Tsaghkashat', 'Tsaghkashat', 'Ծաղկաշատ', 1),
    (22, 'Red Village', 'Village rouge','Կարմիր գյուղ', 1),
    (23, 'Harav', 'Harav','Հարավ', 1),
    (24, 'Hilis', 'Hilis','Հիլիս', 1),
    (25, 'Madatashen', 'Madatashen',   'Մադաթաշեն', 1),
    (26, 'Mkhitarashen', 'Mkhitarashen', 'Մխիթարաշեն', 1),
    (27, 'Moshkhmhat', 'Moshkhmhat',   'Մոշխմհատ', 1),
    (28, 'Nakhijevanik', 'Nakhijevanik', 'Նախիջևանիկ', 1),
    (29, 'Lower Sznek', 'Bas Sznek',    'Ներքին Սզնեք', 1),
    (30, 'Noragyugh', 'Noragyugh',    'Նորագյուղ', 1),
    (31, 'Shosh', 'Shosh','Շոշ', 1),
    (32, 'Ulupap', 'Ulupap', 'Ուլուպապ', 1),
    (33, 'Ughtasar', 'Ughtasar', 'Ուղտասար', 1),
    (34, 'Patara', 'Patara', 'Պատարա', 1),
    (35, 'Jraghatsʻner', 'Jraghatsʻner', 'Ջրաղացներ', 1),
    (36, 'Rev', 'Rev',  'Ռև', 1),
    (37, 'Sarnaghbyur', 'Sarnaghbyur', 'Սառնաղբյուր', 1),
    (38, 'Sardarashen', 'Sardarashen', 'Սարդարաշեն', 1),
    (39, 'Sarushen', 'Sarushen', 'Սարուշեն', 1),
    (40, 'Sghnakh', 'Sghnakh', 'Սղնախ', 1),
    (41, 'Surenavan', 'Surenavan', 'Սուրենավան', 1),
    (42, 'Varazabun', 'Varazabun', 'Վարազաբուն', 1),
    (43, 'Vardadzor', 'Vardadzor', 'Վարդաձոր', 1),
    (44, 'Upper Ghlijbagh', 'Haut Ghlijbagh', 'Վերին Ղլիջբաղ', 1),
    (45, 'Upper Sznek', 'Haut Sznek', 'Վերին Սզնեք', 1),
    (46, 'Pʻarrukh', 'Pʻarrukh', 'Փառուխ', 1),
    (47, 'Kʻaraglukh', 'Kʻaraglukh', 'Քարագլուխ', 1),
    (48, 'Kʻyatʻukʻ', 'Kʻyatʻukʻ', 'Քյաթուկ', 1),
    (49, 'Kʻṙasni', 'Kʻṙasni', 'Քռասնի', 1),

    (50, 'Azokh', 'Azokh', 'Ազոխ', 2),
    (51, 'Aknaghbyur', 'Aknaghbyur', 'Ակնաղբյուր', 2),
    (52, 'Aygostan', 'Aygostan', 'Այգոստան', 2),
    (53, 'Aradzamugh', 'Aradzamugh', 'Առաջամուղ', 2),
    (54, 'Arak’el', 'Arakel', 'Առաքել', 2),
    (55, 'Araksavan', 'Araksavan', 'Արաքսավան', 2),
    (56, 'Arevshat', 'Arevshat', 'Արևշատ', 2),
    (57, 'Banadzor', 'Banadzor', 'Բանաձոր', 2),
    (58, 'Drakhtik', 'Drakhtik', 'Դրախտիկ', 2),
    (59, 'Taghaser', 'Taghaser', 'Թաղասեռ', 2),
    (60, 'Taghot', 'Taghot', 'Թաղոտ', 2),
    (61, 'Khandzadzor', 'Khandzadzor', 'Խանձաձոր', 2),
    (62, 'Khtsaberd', 'Khtsaberd', 'Խծաբերդ', 2),
    (63, 'Tsakuri', 'Tsakouri', 'Ծակուռի', 2),
    (64, 'Tsaghkavank’', 'Tsaghkavank', 'Ծաղկավանք', 2),
    (65, 'Tsamdzor', 'Tsamdzor', 'Ծամձոր', 2),
    (66, 'Karmrakuch', 'Karmrakoutch', 'Կարմրակուճ', 2),
    (67, 'Karmrak’ar', 'Karmrakar', 'Կարմրաքար', 2),
    (68, 'Hadrut’', 'Hadrout', 'Հադրութ', 2),
    (69, 'Hakaku', 'Hakakou', 'Հակակու', 2),
    (70, 'Haykavan', 'Haykavan', 'Հայկավան', 2),
    (71, 'Hartashen', 'Hartashen', 'Հարթաշեն', 2),
    (72, 'Hin Tagher', 'Hin Tagher', 'Հին Թաղեր', 2),
    (73, 'Hogher', 'Hogher', 'Հողեր', 2),
    (74, 'Dzoragyugh', 'Dzoragyugh', 'Ձորագյուղ', 2),
    (75, 'Ghashchilar', 'Ghashchilar', 'Ղաշչիլար', 2),
    (76, 'Mariamadzor', 'Mariamadzor', 'Մարիամաձոր', 2),
    (77, 'Melik’ashen', 'Melikashen', 'Մելիքաշեն', 2),
    (78, 'Mekhakavan', 'Mekhakavan', 'Մեխակավան', 2),
    (79, 'Mets Tagher', 'Mets Tagher', 'Մեծ Թաղեր', 2),
    (80, 'Mokhrenes', 'Mokhrenes', 'Մոխրենես', 2),
    (81, 'Norashen', 'Norashen', 'Նորաշեն', 2),
    (82, 'Ukhtadzor', 'Oukhtadzor', 'Ուխտաձոր', 2),
    (83, 'Petrosashen', 'Petrosashen', 'Պետրոսաշեն', 2),
    (84, 'Plet’ants’', 'Pletants', 'Պլեթանց', 2),
    (85, 'Jraberd', 'Djraberd', 'Ջրաբերդ', 2),
    (86, 'Jrakus', 'Djrakous', 'Ջրակուս', 2),
    (87, 'Saralandzh', 'Saralandj', 'Սարալանջ', 2),
    (88, 'Sarishen', 'Sarishen', 'Սարիշեն', 2),
    (89, 'Spitakashen', 'Spitakashen', 'Սպիտակաշեն', 2),
    (90, 'Vaghaver', 'Vaghaver', 'Վաղավեր', 2),
    (91, 'Vank’', 'Vank', 'Վանք', 2),
    (92, 'Vardashat', 'Vardashat', 'Վարդաշատ', 2),
    (93, 'Tyak’', 'Tyak', 'Տյաք', 2),
    (94, 'Togh', 'Togh', 'Տող', 2),
    (95, 'Tumi', 'Toumi', 'Տումի', 2),
    (96, 'Ts’or', 'Tsor', 'Ցոր', 2),
    (97, 'K’araglukh', 'Karagloukh', 'Քարագլուխ', 2),
    (98, 'K’aring', 'Karing', 'Քարինգ', 2),
    (99, 'Kyurat’agh', 'Kyuratagh', 'Քյուրաթաղ', 2),

    (100, 'Aghabekalandzh', 'Aghabekalandj', 'Աղաբեկալանջ', 3),
    (101, 'Alashan', 'Alashan', 'Ալաշան', 3),
    (102, 'Akanaberd', 'Akanaberd', 'Ականաբերդ', 3),
    (103, 'Aradzadzor', 'Aradzadzor', 'Առաջաձոր', 3),
    (104, 'Garnak’ar', 'Garnakar', 'Գառնաքար', 3),
    (105, 'Getavan', 'Getavan', 'Գետավան', 3),
    (106, 'Drmbon', 'Drmbon', 'Դրմբոն', 3),
    (107, 'Zaglik', 'Zaglik', 'Զագլիկ', 3),
    (108, 'Zardakhach’', 'Zardakhach', 'Զարդախաչ', 3),
    (109, 'Tblghu', 'Tblghou', 'Թբլղու', 3),
    (110, 'T’alish', 'Talish', 'Թալիշ', 3),
    (111, 'Khnkavan', 'Khnkavan', 'Խնկավան', 3),
    (112, 'Tsaghkashen', 'Tsaghkashen', 'Ծաղկաշեն', 3),
    (113, 'Tsmakahogh', 'Tsmakahogh', 'Ծմակահող', 3),
    (114, 'Kichan', 'Kitchan', 'Կիչան', 3),
    (115, 'Kochoghot', 'Kotchoghot', 'Կոճողոտ', 3),
    (116, 'Kusapat', 'Kousapat', 'Կուսապատ', 3),
    (117, 'Hat’erk’', 'Haterk', 'Հաթերք', 3),
    (118, 'Hayad', 'Hayad', 'Հայադ', 3),
    (119, 'Harut’yunagomer', 'Haroutyunagomer', 'Հարությունագոմեր', 3),
    (120, 'Hovtashen', 'Hovtashen', 'Հովտաշեն', 3),
    (121, 'Ghazarahogh', 'Ghazarahogh', 'Ղազարահող', 3),
    (122, 'Ghazanch’i', 'Ghazantchi', 'Ղազանչի', 3),
    (123, 'Chankat’agh', 'Chankatagh', 'Ճանկաթաղ', 3),
    (124, 'Maghavuz', 'Maghavouz', 'Մաղավուզ', 3),
    (125, 'Mataghis', 'Mataghis', 'Մատաղիս', 3),
    (126, 'Martakert', 'Martakert', 'Մարտակերտ', 3),
    (127, 'Mets Shen', 'Mets Shen', 'Մեծ Շեն', 3),
    (128, 'Mehmana', 'Mehmana', 'Մեհմանա', 3),
    (129, 'Mokhrat’agh', 'Mokhratagh', 'Մոխրաթաղ', 3),
    (130, 'Nareshtar', 'Nareshtar', 'Նարեշտար', 3),
    (131, 'Nerk’in Horat’agh', 'Nerkin Horatagh', 'Ներքին Հոռաթաղ', 3),
    (132, 'Nor Aygestan', 'Nor Aygestan', 'Նոր Այգեստան', 3),
    (133, 'Nor Ghazanch’i', 'Nor Ghazantchi', 'Նոր Ղազանչի', 3),
    (134, 'Nor Haykadzhur', 'Nor Haykadjour', 'Նոր Հայկաջուր', 3),
    (135, 'Nor Karmiravan', 'Nor Karmiravan', 'Նոր Կարմիրավան', 3),
    (136, 'Nor Maragha', 'Nor Maragha', 'Նոր Մարաղա', 3),
    (137, 'Nor Seysulan', 'Nor Seysoulan', 'Նոր Սեյսուլան', 3),
    (138, 'Shahmasur', 'Shahmasour', 'Շահմասուր', 3),
    (139, 'Ch’ap’ar', 'Chapar', 'Չափար', 3),
    (140, 'Ch’arek’tar', 'Charektar', 'Չարեքտար', 3),
    (141, 'Chldran', 'Chldran', 'Չլդրան', 3),
    (142, 'Poghosagomer', 'Poghosagomer', 'Պողոսագոմեր', 3),
    (143, 'Vaghouhas', 'Vaghouhas', 'Վաղուհաս', 3),
    (144, 'Vank’', 'Vank', 'Վանք', 3),
    (145, 'Vardadzor', 'Vardadzor', 'Վարդաձոր', 3),
    (146, 'Varnkat’agh', 'Varnkatagh', 'Վարնկաթաղ', 3),
    (147, 'Verin Horat’agh', 'Verin Horatagh', 'Վերին Հոռաթաղ', 3),
    (148, 'Tonashen', 'Tonashen', 'Տոնաշեն', 3),
    (149, 'K’mk’dzor', 'Kmkadzor', 'Քմքաձոր', 3),
    (150, 'K’olatak', 'Kolatak', 'Քոլատակ', 3),

    (151, 'Ashan', 'Ashan', 'Աշան', 4),
    (152, 'Avdur', 'Avdour', 'Ավդուռ', 4),
    (153, 'Berdashên', 'Berdachen', 'Բերդաշեն', 4),
    (154, 'Blblak', 'Blblak', 'Բլբլակ', 4),
    (155, 'Gevorgavan', 'Gevorgavan', 'Գևորգավան', 4),
    (156, 'Gishi', 'Gishi', 'Գիշի', 4),
    (157, 'Emishchan', 'Emichtchan', 'Եմիշճան', 4),
    (158, 'Zardanashên', 'Zardanachen', 'Զարդանաշեն', 4),
    (159, 'Kherkhan', 'Kherkhan', 'Խերխան', 4),
    (160, 'Khnushinak', 'Khnouchinak', 'Խնուշինակ', 4),
    (161, 'Tsovatêgh', 'Tsovategh', 'Ծովատեղ', 4),
    (162, 'Kaghartsi', 'Kaghartsi', 'Կաղարծի', 4),
    (163, 'Karmir Shuka', 'Karmir Chouka', 'Կարմիր Շուկա', 4),
    (164, 'Kavahan', 'Kavahan', 'Կավահան', 4),
    (165, 'Kolkhozashên', 'Kolkhozachen', 'Կոլխոզաշեն', 4),
    (166, 'Haghorti', 'Haghorti', 'Հաղորտի', 4),
    (167, 'Hats’i', 'Hatsi', 'Հացի', 4),
    (168, 'Herher', 'Herher', 'Հերհեր', 4),
    (169, 'Chartar', 'Chartar', 'Ճարտար', 4),
    (170, 'Machkalashên', 'Matchkalachen', 'Մաճկալաշեն', 4),
    (171, 'Martuni', 'Martouni', 'Մարտունի', 4),
    (172, 'Myurishen', 'Myourichen', 'Մյուրիշեն', 4),
    (173, 'Msmna', 'Msmna', 'Մսմնա', 4),
    (174, 'Mushkapat', 'Mouchkapat', 'Մուշկապատ', 4),
    (175, 'Nngi', 'Nngi', 'Ննգի', 4),
    (176, 'Norshên', 'Norchen', 'Նորշեն', 4),
    (177, 'Shêkher', 'Shekher', 'Շեխեր', 4),
    (178, 'Paravatumb', 'Paravatoumb', 'Պառավաթումբ', 4),
    (179, 'Dzhivani', 'Djivani', 'Ջիվանի', 4),
    (180, 'Sargsashên', 'Sargsachen', 'Սարգսաշեն', 4),
    (181, 'Skhtorashên', 'Skhtorachen', 'Սխտորաշեն', 4),
    (182, 'Sos', 'Sos', 'Սոս', 4),
    (183, 'Spitakashên', 'Spitakachen', 'Սպիտակաշեն', 4),
    (184, 'Vazgenashên', 'Vazgenachen', 'Վազգենաշեն', 4),
    (185, 'Varanda', 'Varanda', 'Վարանդա', 4),
    (186, 'Taghavard', 'Taghavard', 'Թաղավարդ', 4),
    (187, 'K’arahundzh', 'Karahoundj', 'Քարահունջ', 4),
    (188, 'K’ert’', 'Kert', 'Քերթ', 4),
    (189, 'Kadzhavan', 'Kajavan', 'Քաջավան', 4),

    (190, 'Barsghishen', 'Barsghishen', 'Բարսղիշեն', 5),
    (191, 'Dadivank’', 'Dadivank', 'Դադիվանք', 5),
    (192, 'Yeghegnut', 'Yeghegnout', 'Եղեգնուտ', 5),
    (193, 'Yeghts’i', 'Yeghtsi', 'Եղցի', 5),
    (194, 'Yerits’ushen', 'Yeritsoushen', 'Երիցուշեն', 5),
    (195, 'Zuar', 'Zouar', 'Զուար', 5),
    (196, 'Lev', 'Lev', 'Լև', 5),
    (197, 'Kharkhap’ut', 'Kharkhapout', 'Խարխափութ', 5),
    (198, 'Tsar', 'Tsar', 'Ծար', 5),
    (199, 'Kotor', 'Kotor', 'Կոտոր', 5),
    (200, 'Havsat’agh', 'Havsatagh', 'Հավսաթաղ', 5),
    (201, 'Nor Baradzhur', 'Nor Baradjour', 'Նոր Բարաջուր', 5),
    (202, 'Nor Getashên', 'Nor Getachen', 'Նոր Գետաշեն', 5),
    (203, 'Nor Erk’edzh', 'Nor Erkedj', 'Նոր Էրքեջ', 5),
    (204, 'Nor Karachinar', 'Nor Karachinar', 'Նոր Կարաչինար', 5),
    (205, 'Nor Manashid', 'Nor Manashid', 'Նոր Մանաշիդ', 5),
    (206, 'Nor Verinshen', 'Nor Verinshen', 'Նոր Վերինշեն', 5),
    (207, 'Ch’ap’ni', 'Chapni', 'Չափնի', 5),
    (208, 'Ts’rtnot', 'Tsrtnot', 'Ցրտնոտ', 5),
    (209, 'K’arvachar', 'Karvachar', 'Քարվաճառ', 5),
    (210, 'K’naravan', 'Knaravan', 'Քնարավան', 5),

    (211, 'Bazlukh', 'Bazloukh', 'Բազլուխ', 6),
    (212, 'Gaght’ut', 'Gaghtout', 'Գաղթուտ', 6),
    (213, 'Gyulistan', 'Gyulistan', 'Գյուլիստան', 6),
    (214, 'Erk’edzh', 'Erkedj', 'Էրքեջ', 6),
    (215, 'T’odan', 'Todan', 'Թոդան', 6),
    (216, 'Khrkhap’or', 'Khrkhaphor', 'Խրխափոր', 6),
    (217, 'Karachinar', 'Karachinar', 'Կարաչինար', 6),
    (218, 'Hay Paris', 'Hay Paris', 'Հայ Պարիս', 6),
    (219, 'Manashid', 'Manashid', 'Մանաշիդ', 6),
    (220, 'Manasinshen', 'Manasinshen', 'Մանասինշեն', 6),
    (221, 'Shahumyan (Nerk’ishên)', 'Shahoumyan (Nerkitchen)', 'Շահումյան (Ներքիշեն)', 6),
    (222, 'Rus Paris', 'Rous Paris', 'Ռուս Պարիս', 6),
    (223, 'Verin Shên (Verishên)', 'Verin Chen (Verichen)', 'Վերին Շեն (Վերիշեն)', 6),

    (224, 'Yeghts’ahogh', 'Yeghtsahogh', 'Եղցահող', 7),
    (225, 'Lisagor', 'Lisagor', 'Լիսագոր', 7),
    (226, 'Tsaghkadzor', 'Tsaghkadzor', 'Ծաղկաձոր', 7),
    (227, 'Kanach’ T’ala', 'Kanach Tala', 'Կանաչ Թալա', 7),
    (228, 'Hinshen', 'Hinchen', 'Հինշեն', 7),
    (229, 'Hunot', 'Hounot', 'Հունոտ', 7),
    (230, 'Ghaybalishen', 'Ghaybalichen', 'Ղայբալիշեն', 7),
    (231, 'Mets Shên', 'Mets Chen', 'Մեծ Շեն', 7),
    (232, 'Shushi', 'Chouchi', 'Շուշի', 7),
    (233, 'K’arin tak', 'Karin tak', 'Քարին տակ', 7),
    (234, 'K’irsavan', 'Kirsavan', 'Քիրսավան', 7),

    (235, 'Step’anakert', 'Stepanakert', 'Ստեփանակերտ', 8),

    (236, 'Alashkert', 'Alachkert', 'Ալաշկերտ', 9),
    (237, 'Aghadzor', 'Aghadzor', 'Աղաձոր', 9),
    (238, 'Aghanus', 'Aghanous', 'Աղանուս', 9),
    (239, 'Aghavnatun', 'Aghavnatoun', 'Աղավնատուն', 9),
    (240, 'Aghavno', 'Aghavno', 'Աղավնո', 9),
    (241, 'Aghbradzor', 'Aghbradzor', 'Աղբրաձոր', 9),
    (242, 'Aghvesahak’', 'Aghvesahak', 'Աղվեսահաք', 9),
    (243, 'Amiryan', 'Amiryan', 'Ամիրյան', 9),
    (244, 'Amutegh', 'Amoutegh', 'Ամուտեղ', 9),
    (245, 'Aygek', 'Aygek', 'Այգեկ', 9),
    (246, 'Aygehovit', 'Aygehovit', 'Այգեհովիտ', 9),
    (247, 'Andokaberd', 'Andokaberd', 'Անդոկաբերդ', 9),
    (248, 'Aparan', 'Aparan', 'Ապարան', 9),
    (249, 'Arakhish', 'Arakhiche', 'Արախիշ', 9),
    (250, 'Arahuts', 'Arahouts', 'Արահուծ', 9),
    (251, 'Artsvashen', 'Artsvachen', 'Արծվաշեն', 9),
    (252, 'Arjadzor (Aghjayaz)', 'Arjadzor (Aghjayaz)', 'Արջաձոր (Աղջայազ)', 9),
    (253, 'Arvakan', 'Arvakan', 'Արվական', 9),
    (254, 'Artashavi', 'Artashavi', 'Արտաշավի', 9),
    (255, 'Bazmatus', 'Bazmatous', 'Բազմատուս', 9),
    (256, 'Barkushat', 'Barkouchat', 'Բարկուշատ', 9),
    (257, 'Berdik', 'Berdik', 'Բերդիկ', 9),
    (258, 'Berdzor', 'Berdzor', 'Բերձոր', 9),
    (259, 'Berk’ni', 'Berkni', 'Բերքնի', 9),
    (260, 'Gahanist', 'Gahanist', 'Գահանիստ', 9),
    (261, 'Gandza', 'Gandza', 'Գանձա', 9),
    (262, 'Getamezh', 'Getamej', 'Գետամեջ', 9),
    (263, 'Getap’', 'Getap', 'Գետափ', 9),
    (264, 'Gihut', 'Gihout', 'Գիհուտ', 9),
    (265, 'Goght’anik', 'Goghtanik', 'Գողթանիկ', 9),
    (266, 'Grham', 'Grham', 'Գրհամ', 9),
    (267, 'Darbnots’', 'Darbnots', 'Դարբնոց', 9),
    (268, 'Ditsmayri', 'Ditsmayri', 'Դիցմայրի', 9),
    (269, 'Doghar', 'Doghar', 'Դողար', 9),
    (270, 'Yeznagomer', 'Yeznagomer', 'Եզնագոմեր', 9),
    (271, 'Yerits’vank’', 'Yeritsvank', 'Երիցվանք', 9),
    (272, 'Yerkat’avork’', 'Yerkatavork', 'Երկաթավորք', 9),
    (273, 'Yervandakert', 'Yervandakert', 'Երվանդակերտ', 9),
    (274, 'Ishkhanadzor', 'Ichkhanadzor', 'Իշխանաձոր', 9),
    (275, 'Lchashen', 'Ltchashen', 'Լճաշեն', 9),
    (276, 'Khach’getik', 'Khatchgetik', 'Խաչգետիկ', 9),
    (277, 'Khach’intap’', 'Khatchintap', 'Խաչինտափ', 9),
    (278, 'Tsaghkaberd', 'Tsaghkaberd', 'Ծաղկաբերդ', 9),
    (279, 'Tsitsernavank’', 'Tsitsernavank', 'Ծիծեռնավանք', 9),
    (280, 'Tsobadzor', 'Tsobadzor', 'Ծոբաձոր', 9),
    (281, 'Katos', 'Katos', 'Կատոս', 9),
    (282, 'Keren', 'Keren', 'Կերեն', 9),
    (283, 'Kovsakan', 'Kovsakan', 'Կովսական', 9),
    (284, 'Kumayri', 'Kumayri', 'Կումայրի', 9),
    (285, 'Krmen', 'Krmen', 'Կրմեն', 9),
    (286, 'Hale', 'Hale', 'Հալե', 9),
    (287, 'Hak', 'Hak', 'Հակ', 9),
    (288, 'Hakari', 'Hakari', 'Հակարի', 9),
    (289, 'Haytagh', 'Haytagh', 'Հայթաղ', 9),
    (290, 'Haykazyan', 'Haykazyan', 'Հայկազյան', 9),
    (291, 'Harar', 'Harar', 'Հարար', 9),
    (292, 'Herik', 'Herik', 'Հերիկ', 9),
    (293, 'Himnashen', 'Himnachen', 'Հիմնաշեն', 9),
    (294, 'Hochants’', 'Hochants', 'Հոչանց', 9),
    (295, 'Hunanav', 'Hounanav', 'Հունանավ', 9),
    (296, 'Dzorats’ik’ (Ziyrik)', 'Dzoratsik (Ziyrik)', 'Ձորացիք (Զիյրիկ)', 9),
    (297, 'Dzorap’', 'Dzorap', 'Ձորափ', 9),
    (298, 'Ghushch’i', 'Ghouchtchi', 'Ղուշչի', 9),
    (299, 'Chepkut', 'Tchepkout', 'Ճեպկուտ', 9),
    (300, 'Mamark’', 'Mamark', 'Մամարք', 9),
    (301, 'Maratuk', 'Maratouk', 'Մարաթուկ', 9),
    (302, 'Margis', 'Margis', 'Մարգիս', 9),
    (303, 'Martiros', 'Martiros', 'Մարտիրոս', 9),
    (304, 'Martunashen', 'Martounachen', 'Մարտունաշեն', 9),
    (305, 'Melik’ashen', 'Melikashen', 'Մելիքաշեն', 9),
    (306, 'Meghvadzor', 'Meghvadzor', 'Մեղվաձոր', 9),
    (307, 'Midzhnavan', 'Midjnavan', 'Միջնավան', 9),
    (308, 'Mirik', 'Mirik', 'Միրիկ', 9),
    (309, 'Mkhants’', 'Mkhants', 'Մխանց', 9),
    (310, 'Msheni', 'Mcheni', 'Մշենի', 9),
    (311, 'Moshat’agh', 'Moshatagh', 'Մոշաթաղ', 9),
    (312, 'Movsesashen', 'Movsesachen', 'Մովսեսաշեն', 9),
    (313, 'Morajur', 'Morajour', 'Մորաջուր', 9),
    (314, 'Mush', 'Mouch', 'Մուշ', 9),
    (315, 'Nerk’in Sus', 'Nerkin Sous', 'Ներքին Սուս', 9),
    (316, 'Noraberd', 'Noraberd', 'Նորաբերդ', 9),
    (317, 'Norashenik', 'Norachenik', 'Նորաշենիկ', 9),
    (318, 'Shalua', 'Shalua', 'Շալուա', 9),
    (319, 'Shamk’', 'Shamk', 'Շամք', 9),
    (320, 'Shirak', 'Chirak', 'Շիրակ', 9),
    (321, 'Shrvakan', 'Chrvakan', 'Շրվական', 9),
    (322, 'Vorduak', 'Vorduak', 'Որդուակ', 9),
    (323, 'Vorotan', 'Vorotan', 'Որոտան', 9),
    (324, 'Urrekan', 'Ourrekan', 'Ուռեկան', 9),
    (325, 'Urmia', 'Ourmia', 'Ուրմիա', 9),
    (326, 'Chormanq', 'Chormank', 'Չորմանք', 9),
    (327, 'Dzhanfida', 'Janfida', 'Ջանֆիդա', 9),
    (328, 'Sahar', 'Sahar', 'Սահառ', 9),
    (329, 'Saratak', 'Saratak', 'Սարատակ', 9),
    (330, 'Set’ants’', 'Setants', 'Սեթանց', 9),
    (331, 'Sthunis', 'Sthounis', 'Սթունիս', 9),
    (332, 'Sonasar', 'Sonasar', 'Սոնասար', 9),
    (333, 'Sus', 'Sous', 'Սուս', 9),
    (334, 'Spitakashen', 'Spitakachen', 'Սպիտակաշեն', 9),
    (335, 'Spitakajur', 'Spitakajour', 'Սպիտակաջուր', 9),
    (336, 'Vazgenashen', 'Vazgenachen', 'Վազգենաշեն', 9),
    (337, 'Vakunnis', 'Vakounis', 'Վակունիս', 9),
    (338, 'Vaghagin', 'Vaghagin', 'Վաղագին', 9),
    (339, 'Van', 'Van', 'Վան', 9),
    (340, 'Vanand', 'Vanand', 'Վանանդ', 9),
    (341, 'Vardabats’', 'Vardabats', 'Վարդաբաց', 9),
    (342, 'Vardut', 'Vardout', 'Վարդուտ', 9),
    (343, 'Verin K’ushanik’', 'Verin Kouchanik', 'Վերին Քուշանիք', 9),
    (344, 'Verinshen', 'Verinchen', 'Վերինշեն', 9),
    (345, 'Vurgavan', 'Vourgavan', 'Վուրգավան', 9),
    (346, 'Tandzatap’', 'Tandzatap', 'Տանձատափ', 9),
    (347, 'Tandzut', 'Tandzout', 'Տանձուտ', 9),
    (348, 'Tigranavan', 'Tigranavan', 'Տիգրանավան', 9),
    (349, 'P’akahan', 'Pakahan', 'Փակահան', 9),
    (350, 'K’ashunik’', 'Kachounik', 'Քաշունիք', 9),
    (351, 'K’arabak', 'Karabak', 'Քարաբակ', 9),
    (352, 'K’aratak', 'Karatak', 'Քարատակ', 9),
    (353, 'K’aregah', 'Karegah', 'Քարեգահ', 9),
    (354, 'K’arotan', 'Karotan', 'Քարոտան', 9),
    (355, 'K’arut', 'Karout', 'Քարուտ', 9);