package org.hishatakaran.backend.mapper;

import org.hishatakaran.backend.entity.DescriptiveCharacteristicReference;
import org.hishatakaran.backend.model.DescriptiveCharacteristicResponseDto;
import org.hishatakaran.backend.model.LanguagesResponseDto;

public class DescriptiveCharacteristicMapper {

    public static DescriptiveCharacteristicResponseDto toDto(DescriptiveCharacteristicReference descriptive) {
        return new DescriptiveCharacteristicResponseDto(
            descriptive.getId(),
            LanguagesResponseDto.of(
                descriptive.getArcheologicalOverviewStratigraphyFindingsHy(),
                descriptive.getArcheologicalOverviewStratigraphyFindingsEn(),
                descriptive.getArcheologicalOverviewStratigraphyFindingsFr()
            ),
            LanguagesResponseDto.of(
                descriptive.getArchitecturalOverviewHy(),
                descriptive.getArchitecturalOverviewEn(),
                descriptive.getArchitecturalOverviewFr()
            ),
            LanguagesResponseDto.of(
                descriptive.getDecorativeAndMonumentalFeaturesCompositionColoursHy(),
                descriptive.getDecorativeAndMonumentalFeaturesCompositionColoursEn(),
                descriptive.getDecorativeAndMonumentalFeaturesCompositionColoursFr()
            ),
            LanguagesResponseDto.of(
                descriptive.getOpeningsWindowsHy(),
                descriptive.getOpeningsWindowsEn(),
                descriptive.getOpeningsWindowsFr()
            ),
            LanguagesResponseDto.of(
                descriptive.getOpeningsEntrancesHy(),
                descriptive.getOpeningsEntrancesEn(),
                descriptive.getOpeningsEntrancesFr()
            ),
            LanguagesResponseDto.of(
                descriptive.getConstructionsHy(),
                descriptive.getConstructionsEn(),
                descriptive.getConstructionsFr()
            ),
            LanguagesResponseDto.of(
                descriptive.getRoofHy(),
                descriptive.getRoofEn(),
                descriptive.getRoofFr()
            ),
            LanguagesResponseDto.of(
                descriptive.getTypeHy(),
                descriptive.getTypeEn(),
                descriptive.getTypeFr()
            ),
            LanguagesResponseDto.of(
                descriptive.getLevelsOfConstructionHy(),
                descriptive.getLevelsOfConstructionEn(),
                descriptive.getLevelsOfConstructionFr()
            ),
            LanguagesResponseDto.of(
                descriptive.getTheBuildingMaterialHy(),
                descriptive.getTheBuildingMaterialEn(),
                descriptive.getTheBuildingMaterialFr()
            ),
            LanguagesResponseDto.of(
                descriptive.getExteriorHy(),
                descriptive.getExteriorEn(),
                descriptive.getExteriorFr()
            ),
            LanguagesResponseDto.of(
                descriptive.getImplementationTechniqueHy(),
                descriptive.getImplementationTechniqueEn(),
                descriptive.getImplementationTechniqueFr()
            ),
            LanguagesResponseDto.of(
                descriptive.getLengthHy(),
                descriptive.getLengthEn(),
                descriptive.getLengthFr()
            ),
            LanguagesResponseDto.of(
                descriptive.getWidthHy(),
                descriptive.getWidthEn(),
                descriptive.getWidthFr()
            ),
            LanguagesResponseDto.of(
                descriptive.getHeightHy(),
                descriptive.getHeightEn(),
                descriptive.getHeightFr()
            ),
            LanguagesResponseDto.of(
                descriptive.getDepthThicknessHy(),
                descriptive.getDepthThicknessEn(),
                descriptive.getDepthThicknessFr()
            ),
            LanguagesResponseDto.of(
                descriptive.getAreaHy(),
                descriptive.getAreaEn(),
                descriptive.getAreaFr()
            ),
            LanguagesResponseDto.of(
                descriptive.getLengthOfSpanHy(),
                descriptive.getLengthOfSpanEn(),
                descriptive.getLengthOfSpanFr()
            ),
            LanguagesResponseDto.of(
                descriptive.getStateOfMonumentHy(),
                descriptive.getStateOfMonumentEn(),
                descriptive.getStateOfMonumentFr()
            ),
            LanguagesResponseDto.of(
                descriptive.getValuationHy(),
                descriptive.getValuationEn(),
                descriptive.getValuationFr()
            )
        );
    }
}